apiVersion: v1
kind: Pod
metadata:
  name: busybox1
spec:
  containers:
    - image: busybox
      command:
        - sleep
        - "3600"
      name: busybox
      volumeMounts:
        - mountPath: /mnt
          name: mypvc
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: pvc1
